### ISSUE TITLE
Make queue type configurable for Broker/Trigger and default to quorum queues wherever possible

### ISSUE THREAD

**Issue by gab-satchi** [knative-sandbox/eventing-rabbitmq#760]
**Problem**
Quorum queues offer fault tolerance and data safety in multi node setups while offering similar performance to classic queues in a single node setup. So it makes sense to switch the default queue type used by Triggers to quorum. 

To maintain backwards compatibility, any existing topologies shouldn't break if the user upgrades to a new version that uses quorum queues by default. Since being able to configure the queue type was the long term goal, we can achieve backwards compatibility and configurability at once with the proposed changes.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
System Operator, System Integrator

**Exit Criteria**
- [x] #789 
- [x] #803 
- [x] #758 
- [x] #759

**Additional context (optional)**
Original issue: #658 

After some discussions, we removed the requirement to configure the following settings via a policy per queue. While they may be useful to users, it would also restrict the user from customizing the policy settings to their needs. Policy priority can be used to override any policies created by our system but that would mean 2 policies for every queue created. That's a misuse of policies which is meant to generally have a one:many relationship with the resources it configures.

~~Queue properties to be set by a policy:~~
- ~~`max-in-memory-length=0` to restrict logs stored in memory~~
- ~~`max-length=10000` to set max size of queue~~
- ~~`overflow=reject-publish` to reject publishing when queue is full~~

**Comment by andrewwebber** [comment]
I was performing some chaos engineering exercises after having reliability issues with the broker. 

Of course could be a configuration missing (replicated queues?) on the cluster side however 1.4.0 does not seem to recover if a 3 node rabbitmq cluster is being rescheduled (maintainence or autoscaling + PodDistruptionBudget). 

Dispatcher seem to crash and the broker-ingress never reconnects. The situation is only resolved by restarting the broker at which point a successful retry logic is initiated within the broker.

In the meantime I have a custom operator that scrapes the logs of dispatchers and brokers and restarts them when appropriate.

Just wondered if this was of interest.

**Comment by gab-satchi** [comment]
Thanks @andrewwebber. Having replicated queues would certainly make the system more resilient but connection issues can still happen and we want to improve on that front. 

> Dispatcher seem to crash and the broker-ingress never reconnects.

We tried to fix this (at least broker-ingress) for 1.4.0 in #534. Do you have a script for the chaos testing you were conducting or was it manually done? I'll move your comment into a new issue so we can try to replicate it ourselves with a 3 node cluster and try n fix for 1.5.0

cc: @gabo1208

**Comment by andrewwebber** [comment]
Thanks @gab-satchi I will use your suggested ticket to continue the conversation
